server:
  port: ${SETTLE_SERVER_PORT:80}
  servlet:
    context-path: /
spring:
   application:
      name: settlement-service
      
   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
          dialect: ${SETTLE_SVC_DB_DIALECT:org.hibernate.dialect.H2Dialect}
          show-sql: true
          jdbc:
            time_zone: UTC
     open-in-view: false
    
   devtools:
       livereload:
           enabled: false
   jackson:
      serialization:
         fail-on-empty-beans: false
         
   datasource:
        url:  ${SETTLE_SVC_DB_URL:jdbc:h2:mem:dbTemp}
        username: ${SETTLE_SVC_DB_USERNAME:sa}
        password: ${SETTLE_SVC_DB_PASSWORD:sa}
        driver-class-name: ${SETTLE_SVC_DB_DRIVER:org.h2.Driver}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service/eureka}
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://eureka-service/eureka}
  instance:
    preferIpAddress: true

waya:
   auth:
     baseurl: ${CONFIG_BASEURL_AUTH:https://services.staging.wayabank.ng/auth-service/api/v1/auth}
     name: AUTHENTICATION-SERVICE
   profile:
     name: SETTLEMENT-AUTH-SERVICE
     baseurl: ${CONFIG_BASEURL_SETTLE:https://services.staging.wayabank.ng/auth-service/api/v1}      
   card:
     cardurl: ${CONFIG_BASEURL_CARD:https://services.staging.wayabank.ng/card-service}
     service: CARD-SERVICE
     contacturl: ${CONFIG_BASEURL_CONTACT:https://services.staging.wayabank.ng/contact-service}
   contact:
      service: CONTACT-SERVICE
   account:
       accounturl: ${CONFIG_BASEURL_VIRACCOUNT:https://services.staging.wayabank.ng/account-service}
       service: ACCOUNT-SERVICE
   notification:
      service: NOTIFICATION-SERVICE
      notificationurl: ${CONFIG_BASEURL_NOTIFICATION:https://services.staging.wayabank.ng/notification-service}
   receipt:
      service: RECEIPT-SERVICE
      receipturl: ${CONFIG_BASEURL_RECEIPT:https://services.staging.wayabank.ng/transaction-receipt}
   service:
     username: tbaadm@wayapaychat.com
     password: fintemp@#123
   settlement:
     secret: WAYA0984SETTLE2022